name: SQL Lint

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - "**/*.sql"
      - ".sqlfluff*"
  push:
    branches: [ develop ]
    paths:
      - "**/*.sql"
      - ".sqlfluff*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install SQLFluff
        run: |
          python -m pip install --upgrade pip
          pip install sqlfluff

      - name: Lint SQL
        run: |
          sqlfluff --version
          sqlfluff lint .
