name: Mark stale issues and PRs

on:
  schedule:
    - cron: "0 2 * * *"  # diariamente 02:00 UTC
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: 30
          days-before-pr-stale: 30
          days-before-issue-close: 7
          days-before-pr-close: 7
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          stale-issue-message: "This issue has been marked as stale due to inactivity."
          stale-pr-message: "This PR has been marked as stale due to inactivity."
